name = "cf-ip-scanner-db-proxy"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "97a2e51e170141bc9771ec5f6dc6147a"

[vars]
API_KEY = "antigravity-secret-key-12345"
